<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href=http://localhost:8080/jenkins/job/test/crazyappium/images/10info.jpg target=_blank>Failed Screen Shot</a>]]>
    </line>
    <line>
      <![CDATA[<img src=http://localhost:8080/jenkins/job/test/crazyappium/images/10info.jpg style=width:30px;height:30px img/>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="110522" started-at="2016-04-27T15:12:24Z" finished-at="2016-04-27T15:14:14Z">
    <groups>
    </groups>
    <test name="192.168.56.102:5555" duration-ms="110522" started-at="2016-04-27T15:12:24Z" finished-at="2016-04-27T15:14:14Z">
      <class name="cn.crazy.appium.testcases.XinChangTaiTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:cn.crazy.appium.testcases.XinChangTaiTest@954b04f]" name="beforeSuite" is-config="true" duration-ms="17" started-at="2016-04-27T23:12:24Z" finished-at="2016-04-27T23:12:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String)[pri:0, instance:cn.crazy.appium.testcases.XinChangTaiTest@954b04f]" name="beforeClass" is-config="true" duration-ms="20208" started-at="2016-04-27T23:12:24Z" finished-at="2016-04-27T23:12:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[192.168.56.102:5555]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4490]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="personInfo()[pri:0, instance:cn.crazy.appium.testcases.XinChangTaiTest@954b04f]" name="personInfo" duration-ms="84923" started-at="2016-04-27T23:12:44Z" finished-at="2016-04-27T23:14:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at cn.crazy.appium.testng.Assertion.fail(Assertion.java:63)
	at cn.crazy.appium.testng.Assertion.assertEquals(Assertion.java:19)
	at cn.crazy.appium.page.PersonInofPage.personChange(PersonInofPage.java:130)
	at cn.crazy.appium.testcases.XinChangTaiTest.personInfo(XinChangTaiTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=http://localhost:8080/jenkins/job/test/crazyappium/images/10info.jpg target=_blank>Failed Screen Shot</a>]]>
            </line>
            <line>
              <![CDATA[<img src=http://localhost:8080/jenkins/job/test/crazyappium/images/10info.jpg style=width:30px;height:30px img/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- personInfo -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:cn.crazy.appium.testcases.XinChangTaiTest@954b04f]" name="afterTest" is-config="true" duration-ms="5376" started-at="2016-04-27T23:14:09Z" finished-at="2016-04-27T23:14:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- cn.crazy.appium.testcases.XinChangTaiTest -->
    </test> <!-- 192.168.56.102:5555 -->
  </suite> <!-- Suite -->
</testng-results>
